language: php

env:
    global:
        - XDEBUG_MODE=coverage

php:
    - 7.3
    - 7.4

install:
    - travis_retry composer install --no-interaction --no-suggest

script:
    - composer test -- --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
    only:
        - main

cache:
    directories:
        - $HOME/.composer/cache
